description: "02 Outline JSON Generation"
evaluateOptions:
  maxConcurrency: 1
  showProgressBar: true
prompts:
  - "file://../prompts.py:PodcastPrompts.outline_prompt"
providers:
  - id: "file://../scripts/nim-provider.py"
    label: "405b"
    config:
      api_base: "https://youngthug.demoz.io"
      model: "meta/llama-3.1-405b-instruct"
      temperature: 0.7
      max_tokens: 1000
tests:
  - description: "Outline JSON Generation"
    vars:
      text: file://../tests/outputs/01_raw_outline_results.json
      schema: file://../tests/schemas/podcast_outline.json
    options:
      transformVars: file://../scripts/get-output.py:get_transform
    storeOutputAs: outline_json_output
    assert:
      - type: is-json
        value: file://../tests/schemas/podcast_outline.json
